### ISSUE TITLE
Fonts for fingerings - investigate.

### ISSUE THREAD

**Issue by lukebakken** [uidaho-bsn/BFF#112]
This was just announced on the contrabassoon mailing list:

---

Several weeks back I mentioned a project to create fonts for woodwind fingering diagrams and that project has reached a point where I'm ready to make it public:

www.legnifont.com

With these fonts you can quickly and easily create a fingering diagram for any reasonably common (and some unreasonably uncommon) woodwind instrument in any word processing application (Word, InDesign, Finale, etc.).  Fingerings are created using home-row typing with the same fingers on the computer keyboard that one would use on the woodwind instrument.

Thanks!

Richard Bobo
Contrabassoonist, Tulsa Symphony Orchestra & Symphony of Northwest Arkansas

**Comment by eduardomourar** [comment]
I would suggest using the [Fiati music font](https://github.com/eduardomourar/fiati) that is based in the Bravura font.
